language: python
python:
    - "2.7"
    - "3.6"
    - "3.7"
    - "3.8"
env:
    - REQUIREMENTS=minimal_requirements.txt
    - REQUIREMENTS=requirements.txt
install:
    - pip install -r $REQUIREMENTS
    - pip install pytest pytest-cov codecov
before_script:
    - "export MPLBACKEND=Agg"
script: 
    - python -m pytest --cov=fgivenx
after_success: 
    - codecov
